[package]
name = "pong"
version = "0.1.0"
authors = ["jonat"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.16"
vulkano-shaders = "0.16"